import { NormalizedTrade } from "@/lib/engine/types";
import { subDays, formatISO, subHours } from "date-fns";

const now = new Date();

export const INITIAL_NORMALIZED_TRADES: NormalizedTrade[] = [
  {
    ticket: "2255275",
    openTime: formatISO(subHours(subDays(now, 0), 4)),
    closeTime: formatISO(subHours(subDays(now, 0), 1)),
    symbol: "XAUUSD",
    direction: "LONG",
    volume: 0.2,
    openPrice: 4081.713,
    closePrice: 4076.081,
    profit: -112.60,
    commission: 0,
    swap: 0,
    rr: null,
    status: "LOSS",
    accountName: "Primary Exness Account",
    accountType: "Pro",
    currency: "USD",
    broker: "Exness",
    stopLoss: 4076.081,
    takeProfit: 4100.467,
    closeReason: "user",
    holdDurationMs: 3 * 3600 * 1000,
  },
  {
    ticket: "2253553",
    openTime: formatISO(subHours(subDays(now, 0), 5)),
    closeTime: formatISO(subHours(subDays(now, 0), 2)),
    symbol: "XAUUSD",
    direction: "LONG",
    volume: 0.2,
    openPrice: 4091.659,
    closePrice: 4093.458,
    profit: 36.00,
    commission: 0,
    swap: 0,
    rr: null,
    status: "WIN",
    accountName: "Primary Exness Account",
    accountType: "Pro",
    currency: "USD",
    broker: "Exness",
    stopLoss: 4091.104,
    takeProfit: 4098.633,
    closeReason: "user",
    holdDurationMs: 3 * 3600 * 1000,
  },
  {
    ticket: "2246803",
    openTime: formatISO(subHours(subDays(now, 1), 6)),
    closeTime: formatISO(subHours(subDays(now, 1), 2)),
    symbol: "XAUUSD",
    direction: "SHORT",
    volume: 0.02,
    openPrice: 4154.142,
    closePrice: 4160.887,
    profit: -13.50,
    commission: 0,
    swap: 0,
    rr: -1.0,
    status: "LOSS",
    accountName: "Primary Exness Account",
    accountType: "Pro",
    currency: "USD",
    broker: "Exness",
    stopLoss: 4160.887,
    takeProfit: 4145.734,
    closeReason: "user",
    holdDurationMs: 4 * 3600 * 1000,
  },
  {
    ticket: "2244698",
    openTime: formatISO(subHours(subDays(now, 2), 8)),
    closeTime: formatISO(subHours(subDays(now, 2), 5)),
    symbol: "XAUUSD",
    direction: "SHORT",
    volume: 0.1,
    openPrice: 4117.645,
    closePrice: 4110.85,
    profit: 68.00,
    commission: 0,
    swap: 0,
    rr: 1.36,
    status: "WIN",
    accountName: "Primary Exness Account",
    accountType: "Pro",
    currency: "USD",
    broker: "Exness",
    stopLoss: 4122.658,
    takeProfit: 4102.1,
    closeReason: "user",
    holdDurationMs: 3 * 3600 * 1000,
  },
  {
    ticket: "2241432",
    openTime: formatISO(subHours(subDays(now, 3), 5)),
    closeTime: formatISO(subHours(subDays(now, 3), 2)),
    symbol: "XAUUSD",
    direction: "SHORT",
    volume: 0.1,
    openPrice: 4114.452,
    closePrice: 4116.351,
    profit: -19.00,
    commission: 0,
    swap: 0,
    rr: -1.0,
    status: "LOSS",
    accountName: "Primary Exness Account",
    accountType: "Pro",
    currency: "USD",
    broker: "Exness",
    stopLoss: 4116.351,
    takeProfit: 4100.363,
    closeReason: "user",
    holdDurationMs: 3 * 3600 * 1000,
  },
  {
    ticket: "2241399",
    openTime: formatISO(subHours(subDays(now, 4), 7)),
    closeTime: formatISO(subHours(subDays(now, 4), 4)),
    symbol: "GBPUSD",
    direction: "LONG",
    volume: 0.15,
    openPrice: 1.33787,
    closePrice: 1.33795,
    profit: 1.20,
    commission: 0,
    swap: 0,
    rr: 0.17,
    status: "WIN",
    accountName: "Primary Exness Account",
    accountType: "Pro",
    currency: "USD",
    broker: "Exness",
    stopLoss: 1.33741,
    takeProfit: 1.33875,
    closeReason: "user",
    holdDurationMs: 3 * 3600 * 1000,
  },
];
