// lib/reports/report-assets.ts
// TradeFourge v4.1 Report Assets & Styling Themes

export const REPORT_THEMES = {
  dark: {
    bgPrimary: [11, 15, 23] as [number, number, number],
    bgSecondary: [17, 23, 38] as [number, number, number],
    bgCard: [21, 28, 46] as [number, number, number],
    textPrimary: [255, 255, 255] as [number, number, number],
    textSecondary: [156, 163, 175] as [number, number, number],
    accentPurple: [124, 58, 237] as [number, number, number],
    accentEmerald: [16, 185, 129] as [number, number, number],
    accentRose: [239, 68, 68] as [number, number, number],
    borderGrid: [31, 41, 61] as [number, number, number],
  },
  light: {
    bgPrimary: [255, 255, 255] as [number, number, number],
    bgSecondary: [248, 250, 252] as [number, number, number],
    bgCard: [241, 245, 249] as [number, number, number],
    textPrimary: [15, 23, 42] as [number, number, number],
    textSecondary: [100, 116, 139] as [number, number, number],
    accentPurple: [109, 40, 217] as [number, number, number],
    accentEmerald: [5, 150, 105] as [number, number, number],
    accentRose: [225, 29, 72] as [number, number, number],
    borderGrid: [226, 232, 240] as [number, number, number],
  },
};

export const BRANDING = {
  companyName: "TradeFourge",
  tagline: "INSTITUTIONAL PERFORMANCE REPORT & TRADE AUDIT",
  footerNotice: "Confidential · Generated by TradeFourge Institutional Analytics Engine",
};
